name: trackify
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.5+40

environment:
  sdk: '>=2.17.0 <3.0.0'

# Dependencies specify other packages that your package needs n order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.13.1
  flutter_phoenix: ^1.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  provider: ^6.0.2
  flutter_styled_toast: ^2.1.3
  http: ^0.13.4
  path_provider: ^2.0.11
  sembast: ^3.2.0
  flutter_launcher_icons: ^0.12.0
  firebase_messaging: ^14.7.4
  flutter_local_notifications: ^9.4.0
  overlay_support: ^2.1.0
  webview_flutter: ^4.2.0
  google_sign_in: ^5.4.0
  google_mobile_ads: ^2.4.0
  url_launcher: ^6.1.2
  flutter_dotenv: ^5.0.2
  timezone: ^0.8.0
  device_info_plus: ^9.0.2
  flutter_native_splash: ^2.2.4
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1

dependency_overrides:
  firebase_core_platform_interface: 4.8.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icon/icon.png'
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: 'assets/icon/adaptive_icon.png'

flutter_native_splash:
  color: '#ffffff'
  image: assets/icon/icon.png

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/icon/icon.png
    - assets/listView/row.png
    - assets/listView/card.png
    - assets/listView/grid.png
    - assets/other/googledrive.png
    - assets/other/mercadolibre.png

    - assets/services/andesmar_cargas.png
    - assets/services/andreani.png
    - assets/services/arg_cargo.png
    - assets/services/balut_express.png
    - assets/services/buspack.png
    - assets/services/cata_cargo.png
    - assets/services/central_de_cargas_terrestres.png
    - assets/services/clicoh.png
    - assets/services/clicpaq.png
    - assets/services/condor_entrella.png
    - assets/services/cooperativa_sportman.png
    - assets/services/correo_argentino.png
    - assets/services/credifin_logistica.png
    - assets/services/crucero_express.png
    - assets/services/cruz_del_sur.png
    - assets/services/dhl.png
    - assets/services/ecapack.png
    - assets/services/el_practico_pack.png
    - assets/services/el_turista_pack.png
    - assets/services/encotrans_express.png
    - assets/services/enviopack.png
    - assets/services/epsa.png
    - assets/services/expreso_lancioni.png
    - assets/services/expreso_malargue.png
    - assets/services/fasttrack.png
    - assets/services/fono_pack.png
    - assets/services/integral_pack.png
    - assets/services/jetmar.png
    - assets/services/md_cargas.png
    - assets/services/nandupack.png
    - assets/services/oca.png
    - assets/services/ocasa.png
    - assets/services/pickit.png
    - assets/services/plusmar.png
    - assets/services/pulqui_pack.png
    - assets/services/rabbione.png
    - assets/services/renaper.png
    - assets/services/rodriguez_hermanos_transportes.png
    - assets/services/ruta_cargo.png
    - assets/services/sendbox.png
    - assets/services/south_post.png
    - assets/services/trans_dan_express.png
    - assets/services/urbano.png
    - assets/services/via_cargo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
